# Generated by Django 4.2 on 2023-05-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_is_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("Student", "Student"), ("Employee", "Employee")],
                max_length=20,
            ),
        ),
    ]
