# Generated by Django 4.2 on 2023-05-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("student", "Student"), ("employee", "Employee")],
                max_length=20,
            ),
        ),
    ]
