# Generated by Django 4.2.1 on 2023-05-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_remove_user_is_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="block_date",
            field=models.DateField(default=None, null=True),
        ),
    ]
