# Generated by Django 4.2 on 2023-05-03 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("following", "0002_bookfollowers_delete_follow"),
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="users_following",
            field=models.ManyToManyField(
                related_name="books_following",
                through="following.BookFollowers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
