# Generated by Django 4.2 on 2023-05-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_alter_book_users_following"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="max_loan_time",
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name="book",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
