# Generated by Django 4.2 on 2023-05-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_book_max_loan_time_book_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
