# Generated by Django 4.2.1 on 2023-05-08 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("following", "0009_rename_book_id_follower_book_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0005_alter_book_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="users_following",
            field=models.ManyToManyField(
                related_name="books_following",
                through="following.Follower",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
