# Generated by Django 4.2 on 2023-05-03 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("copies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="copy",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="copy_loan",
                to="copies.copy",
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="loaner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_copy_loan",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="return_date",
            field=models.DateTimeField(default=None),
        ),
    ]
