# Generated by Django 4.2 on 2023-05-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0004_alter_loan_copy_alter_loan_loaner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="returned_date",
            field=models.BooleanField(default=False),
        ),
    ]
