# Generated by Django 4.2 on 2023-05-04 17:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0005_loan_returned_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loan",
            old_name="returned_date",
            new_name="returned",
        ),
    ]
