# Generated by Django 4.2 on 2023-05-03 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_book_users_following"),
        ("copies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="copy",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="copies",
                to="books.book",
            ),
        ),
    ]
