# Generated by Django 4.2 on 2023-05-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copies", "0002_alter_copy_book"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="copy",
            name="max_loan_time",
        ),
        migrations.AddField(
            model_name="copy",
            name="available",
            field=models.BooleanField(default=True),
        ),
    ]
