# Generated by Django 4.2 on 2023-05-04 14:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0003_alter_book_users_following"),
        ("following", "0002_bookfollowers_delete_follow"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BookFollowers",
            new_name="Followers",
        ),
    ]
