# Generated by Django 4.2 on 2023-05-04 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("following", "0003_rename_bookfollowers_followers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="followers",
            old_name="book",
            new_name="book_id",
        ),
        migrations.RenameField(
            model_name="followers",
            old_name="follower",
            new_name="follower_id",
        ),
    ]
