# Generated by Django 4.2 on 2023-05-04 18:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("following", "0004_rename_book_followers_book_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="followers",
            old_name="follower_id",
            new_name="user_id",
        ),
    ]
