# Generated by Django 4.2 on 2023-05-05 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_alter_book_users_following"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("following", "0006_alter_followers_book_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followers",
            name="book_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_following",
                to="books.book",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="followers",
            unique_together={("book_id", "user_id")},
        ),
    ]
