# Generated by Django 4.2 on 2023-05-05 01:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0003_alter_book_users_following"),
        ("following", "0007_alter_followers_book_id_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Followers",
            new_name="Follower",
        ),
    ]
