# Generated by Django 4.2 on 2023-05-05 12:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0005_alter_book_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("following", "0008_rename_followers_follower"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follower",
            old_name="book_id",
            new_name="book",
        ),
        migrations.RenameField(
            model_name="follower",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AlterUniqueTogether(
            name="follower",
            unique_together={("book", "user")},
        ),
    ]
